services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: disciplo-pocketbase
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: disciplo-telegram-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      pocketbase:
        condition: service_healthy

  frontend:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    container_name: disciplo-frontend
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      - pocketbase
