services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: disciplo-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: disciplo-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      pocketbase:
        condition: service_healthy

  frontend:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
      args:
        POCKETBASE_URL: ${POCKETBASE_URL}
        TELEGRAM_LINK_SECRET: ${TELEGRAM_LINK_SECRET}
        HOST: ${HOST}
        POCKETBASE_PORT: ${POCKETBASE_PORT}
    container_name: disciplo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pocketbase
    volumes:
      - ./sveltekit/src:/app/src:ro  # Mount source files for live development
      - ./sveltekit/static:/app/static:ro  # Mount static assets
