services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: disciplo-pocketbase
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: disciplo-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=pocketbase
      - POCKETBASE_PORT=8090
    depends_on:
      pocketbase:
        condition: service_healthy
    volumes:
      - ./telegram-bot:/app
      - /app/node_modules

  frontend:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    container_name: disciplo-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - HOST=pocketbase
      - POCKETBASE_PORT=8090
    depends_on:
      - pocketbase

networks:
  default:
    name: disciplo-network
