#!/bin/bash

case "$1" in
    "clean")
        echo "🧹 Cleaning pb_data and starting fresh..."
        rm -rf pb_data
        ;;
    *)
        echo "🚀 Starting with existing data..."
        ;;
esac

# Load env vars excluding comments and empty lines
export $(grep -v '^#' ../.env | grep -v '^$' | xargs)
./pocketbase serve
